schemaVersion: 1
sources:
  fabrica:
    repository: https://github.com/fabricahq/public-rules.git
    groups:
      - practices/code-design
      - practices/performance
      - practices/readmes
      - practices/testing
      - techs/go
      - techs/goose
