// Command contentgen renders the Markdown of Rulemart's content pages, each <page>.md in the directory it's given, as
// the <page>.generated.html the web package serves, so the web function links no Markdown renderer. Each generated
// file keeps its page's front matter and template actions as written, and holds its body as HTML; the web package
// reads the front matter and runs the actions when it starts.
package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/renderer/html"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: contentgen <content directory>")
		os.Exit(2)
	}
	if err := generate(os.Args[1]); err != nil {
		fmt.Fprintln(os.Stderr, "contentgen:", err)
		os.Exit(1)
	}
}

// generate writes <page>.generated.html beside each <page>.md in dir.
func generate(dir string) error {
	sources, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return err
	}
	if len(sources) == 0 {
		return fmt.Errorf("no Markdown pages in %s", dir)
	}
	for _, source := range sources {
		page, err := os.ReadFile(source)
		if err != nil {
			return err
		}
		out, err := render(page, filepath.Base(source))
		if err != nil {
			return fmt.Errorf("render %s: %v", source, err)
		}
		if err := os.WriteFile(strings.TrimSuffix(source, ".md")+".generated.html", out, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// markdown is the dialect of content pages: GitHub's, as the catalog renders rules, with headings named by their text
// or by an {#id} after them, and raw HTML kept, since the pages are Rulemart's own.
var markdown = goldmark.New(
	goldmark.WithExtensions(extension.GFM),
	goldmark.WithParserOptions(parser.WithAutoHeadingID(), parser.WithAttribute()),
	goldmark.WithRendererOptions(html.WithUnsafe()),
)

// action matches a template action, which must open and close on one line.
var action = regexp.MustCompile(`\{\{.*?\}\}`)

// render returns the generated file for page, the Markdown source named name: its front matter as written, a note
// that it's generated, and its body as HTML. Each template action in the body comes out as written, in place, and one
// alone in a paragraph comes out without the paragraph, so an {{if}} can choose between whole paragraphs.
func render(page []byte, name string) ([]byte, error) {
	frontMatter, body, err := splitFrontMatter(page)
	if err != nil {
		return nil, err
	}
	// Markdown would escape an action's braces and quotes in a link's address, so each is a placeholder of letters and
	// digits until the body is HTML.
	var actions []string
	body = action.ReplaceAllFunc(body, func(a []byte) []byte {
		actions = append(actions, string(a))
		return []byte(placeholder(len(actions) - 1))
	})
	var rendered bytes.Buffer
	if err := markdown.Convert(body, &rendered); err != nil {
		return nil, err
	}
	out := rendered.String()
	for i, a := range actions {
		p := placeholder(i)
		if !strings.Contains(out, p) {
			return nil, fmt.Errorf("template action %s isn't on the page, as in a link definition nothing uses", a)
		}
		out = strings.ReplaceAll(out, "<p>"+p+"</p>", a)
		out = strings.ReplaceAll(out, p, a)
	}
	var generated bytes.Buffer
	generated.Write(frontMatter)
	fmt.Fprintf(&generated, "<!-- Generated from %s by make generate. Edit %[1]s instead. -->\n", name)
	generated.WriteString(out)
	return generated.Bytes(), nil
}

// placeholder stands for the template action numbered i while the body is Markdown.
func placeholder(i int) string {
	return fmt.Sprintf("RulemartTemplateAction%dEnd", i)
}

// splitFrontMatter returns page's front matter, from its opening --- line through its closing one, and the body after.
func splitFrontMatter(page []byte) (frontMatter, body []byte, err error) {
	const fence = "---\n"
	if !bytes.HasPrefix(page, []byte(fence)) {
		return nil, nil, errors.New("doesn't start with front matter, a --- line")
	}
	end := bytes.Index(page[len(fence):], []byte("\n"+fence))
	if end < 0 {
		return nil, nil, errors.New("front matter has no closing --- line")
	}
	split := len(fence) + end + len("\n"+fence)
	return page[:split], page[split:], nil
}
