// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sitedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLibrary = `-- name: GetLibrary :one
SELECT l.github_id, l.owner, l.name, l.description, l.owner_avatar_url, l.license_expression, l.license_file,
       latest.number AS latest_release, latest.tagged_at AS latest_tagged_at
FROM libraries l
JOIN LATERAL (
    SELECT number, tagged_at FROM library_releases WHERE library_id = l.github_id ORDER BY number DESC LIMIT 1
) latest ON true
WHERE lower(l.owner) = lower($1) AND lower(l.name) = lower($2) AND l.github_id = ANY ($3::bigint[])
`

type GetLibraryParams struct {
	Owner  string
	Name   string
	Vetted []int64
}

type GetLibraryRow struct {
	GithubID          int64
	Owner             string
	Name              string
	Description       string
	OwnerAvatarUrl    string
	LicenseExpression pgtype.Text
	LicenseFile       pgtype.Text
	LatestRelease     int32
	LatestTaggedAt    pgtype.Timestamptz
}

func (q *Queries) GetLibrary(ctx context.Context, arg GetLibraryParams) (GetLibraryRow, error) {
	row := q.db.QueryRow(ctx, getLibrary, arg.Owner, arg.Name, arg.Vetted)
	var i GetLibraryRow
	err := row.Scan(
		&i.GithubID,
		&i.Owner,
		&i.Name,
		&i.Description,
		&i.OwnerAvatarUrl,
		&i.LicenseExpression,
		&i.LicenseFile,
		&i.LatestRelease,
		&i.LatestTaggedAt,
	)
	return i, err
}

const getRule = `-- name: GetRule :one
SELECT v.rule_id, r.group_id, g.name AS group_name, v.title::text AS title, v.impact::text AS impact,
       v.when_to_read::text AS when_to_read, v.html::text AS html, v.major, v.minor, v.patch, v.release,
       published.tagged_at AS published_at
FROM rule_versions v
JOIN rules r ON r.library_id = v.library_id AND r.rule_id = v.rule_id
JOIN library_groups g ON g.library_id = r.library_id AND g.group_id = r.group_id
JOIN library_releases published ON published.library_id = v.library_id AND published.number = v.release
WHERE v.library_id = $1 AND v.rule_id = $2 AND v.html IS NOT NULL
`

type GetRuleParams struct {
	LibraryID int64
	RuleID    string
}

type GetRuleRow struct {
	RuleID      string
	GroupID     string
	GroupName   string
	Title       string
	Impact      string
	WhenToRead  string
	Html        string
	Major       int32
	Minor       int32
	Patch       int32
	Release     int32
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) GetRule(ctx context.Context, arg GetRuleParams) (GetRuleRow, error) {
	row := q.db.QueryRow(ctx, getRule, arg.LibraryID, arg.RuleID)
	var i GetRuleRow
	err := row.Scan(
		&i.RuleID,
		&i.GroupID,
		&i.GroupName,
		&i.Title,
		&i.Impact,
		&i.WhenToRead,
		&i.Html,
		&i.Major,
		&i.Minor,
		&i.Patch,
		&i.Release,
		&i.PublishedAt,
	)
	return i, err
}

const listCurrentRules = `-- name: ListCurrentRules :many
SELECT v.rule_id, r.group_id, v.title::text AS title, v.impact::text AS impact, v.major, v.minor, v.patch
FROM rule_versions v
JOIN rules r ON r.library_id = v.library_id AND r.rule_id = v.rule_id
WHERE v.library_id = $1 AND v.html IS NOT NULL
ORDER BY r.group_id, lower(v.title), v.rule_id
`

type ListCurrentRulesRow struct {
	RuleID  string
	GroupID string
	Title   string
	Impact  string
	Major   int32
	Minor   int32
	Patch   int32
}

func (q *Queries) ListCurrentRules(ctx context.Context, libraryID int64) ([]ListCurrentRulesRow, error) {
	rows, err := q.db.Query(ctx, listCurrentRules, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentRulesRow
	for rows.Next() {
		var i ListCurrentRulesRow
		if err := rows.Scan(
			&i.RuleID,
			&i.GroupID,
			&i.Title,
			&i.Impact,
			&i.Major,
			&i.Minor,
			&i.Patch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.group_id, g.name, g.description, g.when_to_read,
       (SELECT count(*) FROM rules r
        WHERE r.library_id = g.library_id AND r.group_id = g.group_id AND r.retired_in IS NULL) AS rule_count
FROM library_groups g
WHERE g.library_id = $1
ORDER BY g.group_id
`

type ListGroupsRow struct {
	GroupID     string
	Name        string
	Description string
	WhenToRead  string
	RuleCount   int64
}

func (q *Queries) ListGroups(ctx context.Context, libraryID int64) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.WhenToRead,
			&i.RuleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT l.github_id, l.owner, l.name, l.description, l.owner_avatar_url,
       (SELECT count(*) FROM rules r WHERE r.library_id = l.github_id AND r.retired_in IS NULL) AS rule_count
FROM libraries l
WHERE l.github_id = ANY ($1::bigint[])
ORDER BY lower(l.owner), lower(l.name)
`

type ListLibrariesRow struct {
	GithubID       int64
	Owner          string
	Name           string
	Description    string
	OwnerAvatarUrl string
	RuleCount      int64
}

func (q *Queries) ListLibraries(ctx context.Context, vetted []int64) ([]ListLibrariesRow, error) {
	rows, err := q.db.Query(ctx, listLibraries, vetted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLibrariesRow
	for rows.Next() {
		var i ListLibrariesRow
		if err := rows.Scan(
			&i.GithubID,
			&i.Owner,
			&i.Name,
			&i.Description,
			&i.OwnerAvatarUrl,
			&i.RuleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersions = `-- name: ListVersions :many
SELECT v.major, v.minor, v.patch, v.release, v.change, v.summaries, published.tagged_at AS published_at
FROM rule_versions v
JOIN library_releases published ON published.library_id = v.library_id AND published.number = v.release
WHERE v.library_id = $1 AND v.rule_id = $2
ORDER BY v.release DESC
`

type ListVersionsParams struct {
	LibraryID int64
	RuleID    string
}

type ListVersionsRow struct {
	Major       int32
	Minor       int32
	Patch       int32
	Release     int32
	Change      string
	Summaries   []string
	PublishedAt pgtype.Timestamptz
}

func (q *Queries) ListVersions(ctx context.Context, arg ListVersionsParams) ([]ListVersionsRow, error) {
	rows, err := q.db.Query(ctx, listVersions, arg.LibraryID, arg.RuleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVersionsRow
	for rows.Next() {
		var i ListVersionsRow
		if err := rows.Scan(
			&i.Major,
			&i.Minor,
			&i.Patch,
			&i.Release,
			&i.Change,
			&i.Summaries,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
